### ISSUE TITLE
Qt UI Implementation 

### ISSUE THREAD

**Issue by RossMeikleham** [RossMeikleham/PlutoBoy#19]
Using Qt Quick we can create a separate UI from the SDL version.  This allows for more flexibility on the desktop version (menus for settings, debuggers etc.). There is currently no intention to move sound from SDL_Mixer from Blaarg's sound implementation to our own.

Ideally this implementation should be accomplished using the latest Qt version (5.5) and creating QObjects which are wrappers around the c headers/files instead of modifying them to be C++/Qt C++. 

Another bonus is after implementing this it should be simple to port to (IOS #11 )/(Android #12) using Qt and constructing individual UIs through QML.

**Comment by RossMeikleham** [comment]
Would like to keep the project mostly C at the moment, need to rethink implementing this
sometime in the future after the 0.2 release.

**Comment by retuxx** [comment]
> Would like to keep the project mostly C at the moment, need to rethink implementing this
sometime in the future after the 0.2 release.

I think having an emulator implemented in SDL2 is very beneficial. For example, I'm trying to run this emulator on Steam Link. There is no other emulator available for this task. So, please stay at C and SDL2.
