### ISSUE TITLE
3DS build hangs on emulation start

### ISSUE THREAD

**Issue by alice-werefox** [RossMeikleham/PlutoBoy#53]
Hey, so I have a New 3DS and I've been trying for hours to get this working on it.

I've both built the project myself and tried the CI artifacts directly, but neither the .cia nor the .3dsx versions seem to be able to do anything past the start of emultion. The console just hangs, and the only way I can get out of it is to pop the Luna menu and reboot. I've tried running in both modes, changing the directory path, attempting to change file and directory permissions, but nothing seems to be making a difference.

![2023-01-29_11-53-36 963_both](https://user-images.githubusercontent.com/12878429/215347716-50707f96-64d8-4dbe-b1c5-5d63e02b33f0.jpg)

I can post other debug information, if that's helpful. The most I can *maybe* gather on my own is that it might be some kind of permissions issue, as it seems to also be having trouble creating a .sav file when loading SRAM. Adding a premade one in the same directory fixes that error, but it still just hangs.

**Comment by RossMeikleham** [comment]
Sorry, i've not had access to my 3DS for a bit so its taken me a while to reply.

I've just used the recent exported CI ".3dsx" file (which should be the same as yours), and it boots fine for me on my New 3DS 😬 Typical "it works fine on my machine". I wonder if it could be something affected by the 3DS firmware version as i've not updated mine for a while.

Or it could be something affected by firmware, are you using "Luma3DS", or another CFW, would you be able to provide that and the version number so I can get my 3DS into a representative state to hopefully replicate and fix the issue?

**Comment by alice-werefox** [comment]
Oh that's all good information to have, huh? 

Luma3DS, the Pokemon Blue is a direct archive of a cartridge I own, it should work. I have tried other ROMs, but I'm definitely willing to give it another go. I'll check for updates on things and I'll get you some hashes and other info when I'm back at my desk.

**Comment by alice-werefox** [comment]
So, unfortunately, I'm still getting the same results. Updated to Luma 12.0, system is at 11.16.0-49U, using the 3dsx file from CI, and attempting to load both ucity and ucity_compat both give me the same issue. In case it makes any difference whatsoever, I'm using a new 3DS, the pokemon red/blue edition one.

**Comment by RossMeikleham** [comment]
Thanks for testing this! I've updated to Luma 12.0. but I am still not finding any issues  😣  I don't think there's a permission issue as from your screenshot the logs can read the ROM, I wonder if the RAM writing may be an issue, but that doesn't usually occur until a bit after the game ha sstarted. From my mounted SD card on the 2DS the ROMS are at  e.g."/Gameboy/Pokemon_Blue.gb", the system i'm running is a "New 2DS XL" which is a bit different to your New 3DS.

The only thing I can think of is  that the emulator works on new 2DS but fails on other variants for some reason, i'll get a hold of one and see if I can replicate the issue

**Comment by alice-werefox** [comment]
Thank you for following up and being so thorough on this. I'm willing to test anything else you come up with. I think my roommates have some other 3DS variants I can see if they'll let me borrow to test with.

**Comment by alice-werefox** [comment]
.... Well, I tried a new build just on a whim from the actions section and it's working, loaded up [Link's Awakening Redux]() just fine!
![ladx_top](https://user-images.githubusercontent.com/12878429/228347301-7678b7f8-3e43-4eda-9ff0-821c4f3160b8.jpg)
![ladx_bot](https://user-images.githubusercontent.com/12878429/228347305-cc724a9c-aa3b-4e6c-b59f-1f323c198159.jpg)

I wonder what what was about!

**Comment by RossMeikleham** [comment]
Awesome!!, so I think this might be because I docker'ised a lot of the build environments as some of them are quite painful to natively setup, I've had this happen before (and currently with the Vita build as its failing) where my images pull from latest, and the homebrew SDKs sometimes make breaking changes. I think you might have been unlucky and got/built a version of the SDK that was modified that broke something. (Which could possibly explain why my build and your manual build from the same source failed). I'm possibly guessing there was a further update that fixed that. I could be entirely wrong.

What I should do is lock the docker images to a specific version rather than latest, i've done this for a couple of them but should do this for the rest. But glad it is now working for you :)

**Comment by alice-werefox** [comment]
Yeah! No worries, glad it's working. I'd be happy to do more tests for ya if you ever want it. This is a neat project! :P
Anyway, closing, because this is definitely solved as far as I can tell.
